#!/bin/bash

MODE=${1:-TRAINING}
BOT_NAME=${2:-TheBot}
COMPILE_AND_PACKAGE=${3:-false}

if $COMPILE_AND_PACKAGE; then
    mvn compile
    mvn package
fi

mvn exec:java -Dexec.mainClass="main.Main" -Dexec.args="yctb82aw ${MODE} bot.${BOT_NAME}"
